// <auto-generated />

global using FluentAssertions;
global using isdayoff;
global using isdayoff.Contract;
global using Xunit;
global using Loodsen.SalaryCalculator.Abstractions;
global using Loodsen.SalaryCalculator.Models;
global using Loodsen.SalaryCalculator.Services;
global using Moq;
global using MudBlazor;
global using Serilog.Core;