// <auto-generated />

global using System.Globalization;
global using System.Reflection;
global using FluentAssertions;
global using Xunit;
global using Loodsen.SalaryCalculator.Abstractions;
global using Loodsen.SalaryCalculator.Extensions;
global using Loodsen.SalaryCalculator.Models;
global using Loodsen.SalaryCalculator.Services;
global using Loodsen.SalaryCalculator.Tests.Attributes;
global using Moq;
global using MudBlazor;
global using Serilog.Core;
global using Xunit.Sdk;