// <auto-generated />

global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Net;
global using System.Reactive;
global using System.Reactive.Disposables;
global using System.Reactive.Linq;
global using System.Reactive.Subjects;
global using System.Reactive.Threading.Tasks;
global using System.Reflection;
global using DynamicData;
global using DynamicData.Binding;
global using Loodsen.SalaryCalculator.Abstractions;
global using Loodsen.SalaryCalculator.Constants;
global using Loodsen.SalaryCalculator.Extensions;
global using Loodsen.SalaryCalculator.Handlers;
global using Loodsen.SalaryCalculator.Models;
global using Loodsen.SalaryCalculator.Pages.ViewModels;
global using Loodsen.SalaryCalculator.Pages.Views;
global using Loodsen.SalaryCalculator.Services;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.FeatureManagement;
global using MudBlazor;
global using MudBlazor.Services;
global using Polly;
global using Polly.Extensions.Http;
global using Prometheus;
global using ReactiveUI;
global using ReactiveUI.Fody.Helpers;
global using Serilog;
global using Splat;
global using Splat.Serilog;
global using ILogger = Serilog.ILogger;

public interface IMarker { }
